# Generated by Django 5.0.1 on 2024-02-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='module',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='module',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
