# Generated by Django 4.2 on 2024-03-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_votremodeleemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=255),
        ),
    ]
